extern "C" {
#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>
}

#include <iostream>

// Forward declaration of binding function generated by tsujikiri
void register_bullet3(lua_State* L);

int main()
{
    // Initialize Lua
    lua_State* L = luaL_newstate();
    luaL_openlibs(L);

    // Register Bullet3 bindings
    register_bullet3(L);

    // Load and execute the Bullet3 demo script
    int result = luaL_dofile(L, BULLET3_DEMO_SCRIPT);
    if (result != LUA_OK)
    {
        std::cerr << "Error: " << lua_tostring(L, -1) << std::endl;
        lua_pop(L, 1);
    }

    // Clean up
    lua_close(L);

    return result == LUA_OK ? 0 : 1;
}